version: '3'

services:

  course:

    container_name: course-service

    restart: always

    build: ./course-service

    ports:

      - '3001:3000'

    links:

      - mongo

  student:

    container_name: student-service

    restart: always

    build: ./student-service

    ports:

      - '3002:3000'

    links:

      - mongo


  mongo:

    container_name: mongo

    image: mongo

    ports:

      - '27017:27017'


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - student
      - course
